version: '2'
services:
    web:
        build: . 
        image: hook-redmine
        container_name: hook-redmine
        ports:
            - "5000:5000"
        volumes:
            - ${PWD}/conf.txt:/home/conf.txt



